# Generated by Django 4.1.7 on 2023-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
